### ISSUE TITLE
Road to AnimeGo Re

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeGo-Re#19]
# Complete rewrite in Flutter
The entire app will be rewritten in Flutter. The old implementation was too hard to update and maintain so I decided to rewrite it. This app was originally written back in 2017 as my first react native app. I haven't used it for a really long time because I found a better site but it doesn't have much great anime so I decided to use this app again. With the power of Flutter, I can port it to Mac OS and even Windows. However, the webview won't work so the experience wasn't as good as the mobile version.

## UX experience
I am quite satisfied so far. The watching experience is great and no popups but still you can get some messages from the website. This is what I always wanted 2 years ago.

## Logo update
The logo will have a deep orange colour to replace the old orange colour.

## Tablet support
I will write an alternative interface for tablets or any devices with a large screen. Currently, I own two tablets and I use them quite a lot so it might be great to support tablets.

# TODO
- [x] ~~Use a list instead of hardcode for tablet home page (I don't know what I was thinking)~~ maybe in 1.3
- [x] Android devices have the option to watch in other apps.
- [x] Recreate old UI
   - [x] AnimeGrid (this is reused intensively for almost all screens)
   - [x] AnimeCard (it renders the card for each entry and pushes to either episode or details) 
   - [x] Episode (one single page with many sources)
   - [x] DetailedAnime (detailed info for that anime and renders all episodes)
   - [x] Watch anime in-app with a webview which blocks all popups
- [x] Better navigation with a drawer (works great on all platforms)
- [x] Update domain automatically
- [x] Check for update automatically and manually (fortnightly)
- [x] Better tablet experience (it is already pretty great)
- [x] More animations wherever possible
- [X] Save watch history by combining BasicAnime and OneEpisodeInfo
- [x] Save favourite anime (~~at least the cover image~~ only title and link)
- [x] ~~press ESC to go back on desktop or web (wrap around some widget)~~ deprecated
- [x] ~~Only use gestures on iOS and improve the detection system (no need on Android)~~ IOS has a built-in player so I put the app bar for it
- [x] Update bottom navigation bar colour according to the theme of android 
- [x] Add a horizontal list in seasonal to check all older seasons (2020, 2019, now all the way till 2014 so 6 years) 
- [x] Added pull to refresh
- [x] Option to hide dub and mark dub in the front
- [x] ~~Option to change to dark mode manually~~ maybe later
- [x] Show some texts to inform users whether an episode has been watched

I have used it quite a lot this season (summer 2020). Watch history and favourite anime are also added. I say it is close to an official release.

**Comment by HenryQuan** [comment]
Finally, it is done. I will test it a bit more and release it later.
